In [1]:
import numpy as np


In [2]:
python_list=[1,2,3,5,6,7]
array=np.array(python_list)
print(array)

[1 2 3 5 6 7]


In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros((10,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [5]:
random_generator=np.random.default_rng()

In [6]:
random_generator.normal(loc=0, scale=1)

-1.306234341126566

In [7]:
one_d_array=np.arange(10)
one_d_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
one_d_array[::2]

array([0, 2, 4, 6, 8])

In [11]:
one_d_array[1:4]

array([1, 2, 3])

In [12]:
one_d_array[7::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
one_d_array[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
random_generator_seed=np.random.default_rng(23444)
 

In [14]:
low=0 
high=10
size=(3,4)
two_d_array=random_generator_seed.uniform(low,high,size)
two_d_array

array([[3.19001165, 6.23494067, 7.15260982, 7.25559343],
       [0.86071593, 0.94199564, 6.92112831, 1.78065388],
       [4.14657673, 3.29445207, 2.85390505, 4.30645489]])

In [15]:
mask_great_5 = two_d_array > 5
mask_great_5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [16]:
two_d_array[mask_great_5]

array([6.23494067, 7.15260982, 7.25559343, 6.92112831])

In [17]:
a=np.array([0,2,5])
b=np.array([5,5,3])
a+b

array([5, 7, 8])

In [18]:
a=np.array([0,2,5])
b=5
a+b

array([ 5,  7, 10])

In [19]:
import pandas as pd

In [20]:
lista = [0.25, 0.5, 0.75, 1]
data = pd.Series(lista)
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [21]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [22]:
population_dict = {"california":485629, "texas": 87349129, "new york":7324024423}
population = pd.Series(population_dict)
population

california        485629
texas           87349129
new york      7324024423
dtype: int64

In [23]:
population["california":"texas"]

california      485629
texas         87349129
dtype: int64

In [24]:
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [27]:
pd.Series({2:"a", 1:"b", 3:"c"}, index=[2,2,1,3,3,3])

2    a
2    a
1    b
3    c
3    c
3    c
dtype: object

In [28]:
area_dict = {"california":234567890, "texas":456789876, "argentina":986798766789}
states_pop = {"california":456789087, "texas":9766787445}

area=pd.Series(area_dict)
pop=pd.Series(states_pop)

state=pd.DataFrame({"population":pop, "area":area})
state

population          area
argentina            NaN  986798766789
california  4.567891e+08     234567890
texas       9.766787e+09     456789876

In [29]:
data1 = {"cliente" : ["a", "b", "c", "d"], 
         "ventas": [100, 200, 300, 400]}
data2 = {"cliente" : ["c", "d", "e", "f"], 
         "ventas": [700, 300, 300, 900]}

df1=pd.DataFrame(data1).set_index("cliente")
df2=pd.DataFrame(data2).set_index("cliente")
df2

ventas
cliente        
c           700
d           300
e           300
f           900

In [30]:
unique_index1=df1.index.unique()
unique_index2=df2.index.unique()
print(unique_index1)
print(unique_index2)

Index(['a', 'b', 'c', 'd'], dtype='object', name='cliente')
Index(['c', 'd', 'e', 'f'], dtype='object', name='cliente')


In [32]:

intersection=unique_index1.intersection(unique_index2)
intersection

Index(['c', 'd'], dtype='object', name='cliente')

In [34]:
difference=unique_index1.difference(unique_index2)
difference

Index(['a', 'b'], dtype='object', name='cliente')

In [35]:
union=unique_index1.union(unique_index2)
union

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object', name='cliente')